apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethereum-data-fetcher
  namespace: default
  labels:
    app: ethereum-data-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ethereum-data-fetcher
  template:
    metadata:
      labels:
        app: ethereum-data-fetcher
    spec:
      containers:
      - name: ethereum-data-fetcher
        env:
        - name: EVENT_FILTER
          value: FailedGetResourceMetric,FailedComputeMetricsReplicas,Unhealthy,Failed,Killing,Scheduled,Pulled,Started,Created
        - name: SLACK_API_URL
          value: https://hooks.slack.com/services/RANDOM12/BFMADBNDS/0cYHvK1a9xviCsjakjawTMaa
        - name: SLACK_TEXT
          value: "ethereum-data-fetcher:"
        image: ethereum-data-fetcher:36
        command: ["/ethereum-data-fetcher"]
        args:
        - --logtostderr
        - -v=4
         2>&1
